# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "IRCdiscord-${version}";
  version = "0.0.0";

  goPackagePath = "github.com/tadeokondrak/IRCdiscord";

  src = ./.;

  goDeps = ./deps.nix;
}
