# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/bwmarrin/discordgo";
    fetch = {
      type = "git";
      url = "https://github.com/bwmarrin/discordgo";
      rev = "8325a6bf6dd6c91ed4040a1617b07287b8fb0eba";
      sha256 = "1gd3j1zi5vqyk5k5knlhmka4d1cr6zx24zwsqhjjksq5l7xyl9h8";
    };
  }
  {
    goPackagePath = "github.com/dustin/go-humanize";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/go-humanize";
      rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e";
      sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3";
    };
  }
  {
    goPackagePath = "github.com/google/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/google/uuid";
      rev = "9b3b1e0f5f99ae461456d768e7d301a7acdaa2d8";
      sha256 = "0yx4kiafyshdshrmrqcf2say5mzsviz7r94a0y1l6xfbkkyvnc86";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "7c8e298727d149d7c329b4dec7e94e1932ac5c11";
      sha256 = "0d84bzjng0s9yq3jq7m8hzj0q7djkzyz1shnbsiazxibdaz768xh";
    };
  }
  {
    goPackagePath = "github.com/tadeokondrak/irc";
    fetch = {
      type = "git";
      url = "https://github.com/tadeokondrak/irc";
      rev = "0b0ea71e5b7a7e1c69a80e7ace1c964582755079";
      sha256 = "162z745550wr23aw264mhz60wx57bidwzp31m07lpfdpda5fl8wy";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "193df9c0f06f8bb35fba505183eaf0acc0136505";
      sha256 = "0rs0dwgjk8zsjqln312sj0sfj1c08bpm46nk1jphch8jzh9kc03b";
    };
  }
]
